# Generated by Django 3.2.14 on 2023-04-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0002_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('delivery_person_name', models.CharField(max_length=255)),
                ('d_House', models.CharField(max_length=255)),
                ('d_City', models.CharField(max_length=20)),
                ('d_state', models.CharField(max_length=20)),
                ('d_country', models.CharField(max_length=20)),
                ('d_phone', models.CharField(max_length=20)),
                ('d_email', models.CharField(max_length=20)),
                ('from_address', models.CharField(max_length=255)),
                ('weight', models.FloatField(null=True)),
                ('book_date', models.DateField(auto_now_add=True)),
                ('pickup_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('status_2', models.CharField(max_length=20, null=True)),
                ('status_3', models.CharField(max_length=20, null=True)),
                ('trackid', models.CharField(max_length=20, null=True)),
                ('complation_status', models.BooleanField(default=False)),
                ('order_taken', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
