# Generated by Django 3.2.14 on 2023-04-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_goodbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodbooking',
            name='itemtype',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodbooking',
            name='staff_person',
            field=models.IntegerField(null=True),
        ),
    ]
