# Generated by Django 3.2.14 on 2023-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20230422_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodbooking',
            name='company',
            field=models.IntegerField(null=True),
        ),
    ]
