# Generated by Django 3.2.14 on 2023-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_goodbooking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodbooking',
            name='deliverd_date',
            field=models.DateField(null=True),
        ),
    ]
